# A headless service to create DNS records.
apiVersion: v1
kind: Service
metadata:
  name: hdfs-namenode
  labels:
    app: hdfs-namenode
spec:
  ports:
  - port: 8020
    name: fs
  clusterIP: None
  selector:
    app: hdfs-namenode
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: hdfs-namenode
spec:
  serviceName: "hdfs-namenode"
  replicas: 1
  template:
    metadata:
      labels:
        app: hdfs-namenode
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: hdfs-namenode
          image: gcr.io/ivynet-containers/hadoop-nn:2.8.5
          imagePullPolicy: Always
          resources:
            requests:
              memory: 10Gi
              cpu: 1500m
            limits:
              memory: 10Gi
          env:
            - name: CLUSTER_NAME
              value: hdfs-k8s
            - name: HADOOP_HEAPSIZE
              value: "8192"
          ports:
          - containerPort: 8020
            name: fs
          volumeMounts:
          - name: namedir
            mountPath: /hadoop/dfs/name
      restartPolicy: Always
      nodeSelector:
          beta.kubernetes.io/instance-type: n1-highmem-2
  volumeClaimTemplates:
  - metadata:
      name: namedir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi
